DROP TABLE IF EXISTS "inventory_movements" CASCADE;
DROP TABLE IF EXISTS "order_items" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "stock_records" CASCADE;
DROP TABLE IF EXISTS "product_models" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "purchase_items" CASCADE;
DROP TABLE IF EXISTS "purchase_batches" CASCADE;
DROP TABLE IF EXISTS "buyers" CASCADE;
DROP TABLE IF EXISTS "suppliers" CASCADE;
DROP TYPE IF EXISTS "order_status" CASCADE;

CREATE TYPE "order_status" AS ENUM (
  'pending',
  'shipped',
  'delivered', 
  'confirmed',
  'confirmed_in_trial',
  'canceled'
);

CREATE TABLE "suppliers" (
  "supplier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_name" varchar,
  "contact_info" varchar,
  "created_at" timestamp
);

CREATE TABLE "buyers" (
  "buyer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_account" varchar
);

CREATE TABLE "purchase_batches" (
  "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "created_at" timestamp,
  "expect_date" timestamp,
  "status" varchar,
  FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id")
);

CREATE TABLE "purchase_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" int,
  "model_id" int,
  "quantity" int,
  "unit_cost" decimal,
  "note" varchar,
  FOREIGN KEY ("batch_id") REFERENCES "purchase_batches" ("batch_id")
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar,
  "listed_date" date,
  "status" varchar
);

CREATE TABLE "product_models" (
  "model_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "model_name" varchar UNIQUE,
  "original_price" decimal,
  "promo_price" decimal,
  "created_at" timestamp,
  FOREIGN KEY ("product_id") REFERENCES "products" ("product_id")
);

CREATE TABLE "stock_records" (
  "model_id" int PRIMARY KEY,
  "stock_quantity" int,
  "last_updated" timestamp,
  FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id")
);

CREATE TABLE "orders" (
  "order_id" varchar PRIMARY KEY,
  "buyer_id" int,
  "product_total_price" decimal,
  "shipping_fee" decimal,
  "total_paid" decimal,
  "order_status" order_status,
  "created_at" timestamp,
  "payment_time" timestamp,
  "shipped_at" timestamp,
  "completed_at" timestamp,
  FOREIGN KEY ("buyer_id") REFERENCES "buyers" ("buyer_id")
);

CREATE TABLE "order_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar,
  "product_id" int,
  "model_id" int,
  "quantity" int,
  "returned_quantity" int,
  "sold_price" decimal,
  "total_price" decimal,
  FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id"),
  FOREIGN KEY ("product_id") REFERENCES "products" ("product_id"),
  FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id")
);