-- Drop existing tables and types
DROP TABLE IF EXISTS "inventory_movements" CASCADE;
DROP TABLE IF EXISTS "order_items" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "stock_records" CASCADE;
DROP TABLE IF EXISTS "product_models" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "purchase_items" CASCADE;
DROP TABLE IF EXISTS "purchase_batches" CASCADE;
DROP TABLE IF EXISTS "buyers" CASCADE;
DROP TABLE IF EXISTS "suppliers" CASCADE;
DROP TYPE IF EXISTS "order_status" CASCADE;

-- Create new enum type
CREATE TYPE "order_status" AS ENUM (
  'pending',           -- 訂單剛成立，尚未處理
  'shipped',           -- 已出貨
  'delivered',         -- 已送達
  'confirmed',         -- 已成立（買家已付款）
  'confirmed_in_trial', -- 已成立（鑑賞期內）
  'canceled'           -- 不成立
);

-- Create suppliers table
CREATE TABLE "suppliers" (
  "supplier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_name" varchar,
  "contact_info" varchar,
  "created_at" timestamp
);

-- Create buyers table
CREATE TABLE "buyers" (
  "buyer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_account" varchar
);

-- Create purchase_batches table (進貨單)
CREATE TABLE "purchase_batches" (
  "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "created_at" timestamp,
  "expect_date" timestamp,
  "status" varchar,   -- draft / confirmed
  FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id")
);

-- Create purchase_items table (進貨明細)
CREATE TABLE "purchase_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" int,
  "model_id" int,
  "quantity" int,
  "unit_cost" decimal,
  "note" varchar,     -- 備註
  FOREIGN KEY ("batch_id") REFERENCES "purchase_batches" ("batch_id")
);

-- Create products table (商品種類)
CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar,
  "listed_date" date,
  "status" varchar    -- e.g., active, inactive, out-of-stock
);

-- Create product_models table
CREATE TABLE "product_models" (
  "model_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "model_name" varchar UNIQUE,
  "original_price" decimal,
  "promo_price" decimal,
  "created_at" timestamp,
  FOREIGN KEY ("product_id") REFERENCES "products" ("product_id")
);

-- Create stock_records table
CREATE TABLE "stock_records" (
  "model_id" int PRIMARY KEY,
  "stock_quantity" int,
  "last_updated" timestamp,
  FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id")
);

-- Create orders table
CREATE TABLE "orders" (
  "order_id" varchar PRIMARY KEY,
  "buyer_id" int,
  "product_total_price" decimal,
  "shipping_fee" decimal,
  "total_paid" decimal,
  "order_status" order_status,
  "created_at" timestamp,                 -- 訂單成立日期
  "payment_time" timestamp,              -- 買家付款時間
  "shipped_at" timestamp,                -- 實際出貨時間
  "completed_at" timestamp,              -- 訂單完成時間
  FOREIGN KEY ("buyer_id") REFERENCES "buyers" ("buyer_id")
);

-- Create order_items table (訂單明細)
CREATE TABLE "order_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar,
  "product_id" int,
  "model_id" int,
  "quantity" int,
  "returned_quantity" int,
  "sold_price" decimal,
  "total_price" decimal,
  FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id"),
  FOREIGN KEY ("product_id") REFERENCES "products" ("product_id"),
  FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id")
); 