CREATE TYPE "order_status" AS ENUM (
  'pending',
  'shipped',
  'delivered',
  'confirmed',
  'confirmed_in_trial',
  'canceled'
);

CREATE TABLE "suppliers" (
  "supplier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_name" varchar,
  "contact_info" varchar,
  "created_at" timestamp
);

CREATE TABLE "buyers" (
  "buyer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_account" varchar
);

CREATE TABLE "purchase_batches" (
  "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "created_at" timestamp,
  "status" varchar
);

CREATE TABLE "purchase_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" int,
  "model_id" int,
  "quantity" int,
  "unit_cost" decimal
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar,
  "parent_id" int
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar,
  "category_id" int,
  "listed_date" date,
  "status" varchar
);

CREATE TABLE "product_models" (
  "model_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "model_name" varchar,
  "sku" varchar UNIQUE,
  "original_price" decimal,
  "promo_price" decimal,
  "created_at" timestamp
);

CREATE TABLE "stock_records" (
  "model_id" int PRIMARY KEY,
  "stock_quantity" int,
  "last_updated" timestamp
);

CREATE TABLE "inventory_movements" (
  "movement_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_id" int,
  "order_id" varchar,
  "movement_type" varchar,
  "quantity" int,
  "created_at" timestamp,
  "note" text
);

CREATE TABLE "orders" (
  "order_id" varchar PRIMARY KEY,
  "buyer_id" int,
  "product_total_price" decimal,
  "shipping_fee" decimal,
  "total_paid" decimal,
  "order_status" order_status,
  "cancel_reason" varchar,
  "return_refund_status" varchar,
  "created_at" timestamp,
  "payment_time" timestamp,
  "shipped_at" timestamp,
  "completed_at" timestamp
);

CREATE TABLE "order_items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar,
  "product_id" int,
  "model_id" int,
  "quantity" int,
  "returned_quantity" int,
  "sold_price" decimal,
  "total_price" decimal
);

ALTER TABLE "purchase_batches" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id");

ALTER TABLE "purchase_items" ADD FOREIGN KEY ("batch_id") REFERENCES "purchase_batches" ("batch_id");

ALTER TABLE "purchase_items" ADD FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("category_id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "product_models" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stock_records" ADD FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id");

ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("buyer_id") REFERENCES "buyers" ("buyer_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("model_id") REFERENCES "product_models" ("model_id");
